title: "Your paper title"
description: "Single-page project display"
url: "https://ddmeer.github.io"
baseurl: "/gemholm"
permalink: pretty
markdown: kramdown
theme: null
plugins: []


links:
  demo: "https://your-demo.example.com"
  pdf:  "https://arxiv.org/pdf/1706.03762.pdf"
  code: "https://github.com/ddmeer/gemholm"
  arxiv: "https://arxiv.org/abs/xxxx.xxxxx"


