title: "你的论文标题"
description: "单页项目展示"
url: "https://ddmeer.github.io"
baseurl: "/gemholm"
permalink: pretty
markdown: kramdown
theme: null
plugins: []


links:
  demo: "https://your-demo.example.com"
  pdf:  "/assets/papers/paper.pdf"
  code: "https://github.com/ddmeer/gemholm"
  arxiv: "https://arxiv.org/abs/xxxx.xxxxx"


